config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end
  
  root "homes#show"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :groups, only: [:index, :show]
  resources :sources, only: [:create, :show, :edit, :update, :destroy]
  resources :feed_entries, only: [:destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
end

app/models/feed_entry.rb
class FeedEntry < ActiveRecord::Base
  belongs_to :user
  belongs_to :source
end

app/models/feed_factory.rb
class FeedFactory
  attr_reader :new_source

  def initialize(user, feed_url)
    @user = user
    feed = fetch_parse(feed_url)
    source = find_or_create_source(feed)
    save_source(source)
    add_feed_entries(source, feed.entries)
  end

  private

  def fetch_parse(feed_url)
    Feedjira::Feed.fetch_and_parse(feed_url)
  end

  def find_or_create_source(feed)
    @user.sources.
      create_with(source_params(feed)).
      find_or_initialize_by(name: feed.title)
  end

  def save_source(source)
    @new_source = source.new_record?
    source.save
  end

  def add_feed_entries(source, entries)
    entries.each do |entry|
      if entry.published > source.updated_at || @new_source
        @user.feed_entries.
          create(feed_params(source, entry))
      end
    end
    source.update(last_modified: Time.now)
  end

  def source_params(feed)
    {
      name: feed.title,
      etag: feed.etag,
      url: feed.url,
      feed_url: feed.feed_url,
      last_modified: Time.now
    } 
  end

  def feed_params(source, entry)
    {
      name: entry.title,
      content: entry.content || entry.summary,
      url: entry.url,
      published_at: entry.published,
      source_id: source.id,
      guid: entry.id
    }
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
end

app/models/source.rb
class Source < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  has_many :feed_entries

  validates :feed_url, uniqueness: {scope: :user_id, message: "Already Exists." }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :feed_entries
  has_many :sources
  has_many :groups

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  def content_feed
    update_user_feed
    show_user_feed
  end

  private

  def update_user_feed
    self.sources.each do |source|
      FeedFactory.new(self, source.feed_url)
    end
  end

  def show_user_feed
    FeedEntry.where(user_id: id).order(published_at: :desc).limit(20) || []
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers

  before_action :require_login
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @feed_entries = current_user.content_feed
    @source = Source.new
  end
end

app/controllers/feed_entries_controller.rb
class FeedEntriesController < ApplicationController
  def destroy
    feed_entry = FeedEntry.find(params[:id])
    feed_entry.destroy
    redirect_to root_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
    @sources = current_user.sources.where(group_id: nil)
  end

  def show
    @group = Group.find(params[:id])
    @sources = current_user.sources.where(group_id: @group.id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :require_login

  def show
    @user = User.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  def index
    @sources = Source.all
  end

  def create
    feed = add_feed
    unless feed.new_source
      flash[:notice] = "Already Subscribed"
    end
    redirect_to dashboard_path
  end

  def show
    @source = Source.find(params[:id])
  end

  def edit
    @source = Source.find(params[:id])
  end

  def update
    @source = Source.find(params[:id])
    @source.update(source_params)
    redirect_to @source
  end

  def destroy
    source = Source.find(params[:id])
    source.feed_entries.destroy_all
    source.destroy
    redirect_to sources_path
  end

  private

  def add_feed
    FeedFactory.new(current_user, feed_url)
  end

  def feed_url
    source_params[:feed_url]
  end

  def source_params
    params.require(:source).permit(:feed_url, :group_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/application/_navigation.html.erb
<%= link_to "Visual RSS", root_path %>
<% if signed_in? %>
  <%= link_to "Subscription List", groups_path %>
  <%= current_user.email %>
  <%= link_to "Sign out", session_path, method: :delete %>
<% end %>

app/views/application/_no_sources.html.erb
<p>Looks like you don't have any subscriptions in your list yet!</p>
<p>To add a new feed to your list, add a feed url into the form above.</p>

app/views/application/_sign_in.html.erb
<h3>Sign In</h3>

<%= form_for :session, url: session_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit "Sign in" %>
  </div>
<% end %>

app/views/application/_sign_up.html.erb
<h3>Sign Up</h3>

<%= form_for user do |form| %>

  <% if user.errors.any? %>
    <%= pluralize(user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/dashboards/show.html.erb
<%= form_for(@source) do |form| %>
  <%= form.text_field :feed_url, placeholder: "New Feed" %>
  <%= form.submit "Add" %>
<% end %>

<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<h1>Latest Posts</h1>
<%= render(@feed_entries) or render("no_sources") %>

app/views/feed_entries/_feed_entry.html.erb
<%= div_for(feed_entry) do %>
  <%= link_to feed_entry.name, feed_entry.url %> 
  by <%= link_to feed_entry.source.name, feed_entry.source.url %>
  posted <%= feed_entry.published_at %>
  [<%= link_to "X", feed_entry, method: :delete %>]
  <%= feed_entry.source.updated_at %>
<% end %>

app/views/groups/_group.html.erb
<%= div_for(group) do %>
  <%= link_to group.name, group %>
<% end %>

app/views/groups/index.html.erb
<h1>Subscriptions List</h3>

<p>Categories</p>
<%= render @groups %>

<p>Uncategorized</p>
<%= render @sources %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>
<%= render @sources %>

app/views/homes/show.html.erb
<%= render "sign_in" %>
<%= render "sign_up", user: @user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Appx</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <%= render "navigation" %>
    </header>

    <%= yield %>

  </body>
</html>

app/views/sources/_source.html.erb
<%= div_for(source) do %>
  <%= link_to source.name, source %>
  [<%= link_to "X", source, method: :delete %>]
<% end %>

app/views/sources/edit.html.erb
<h1>Edit <%= @source.name %></h1>

<%= form_for(@source) do |form| %>
  <% current_user.groups.each do |group| %>
    <%= form.radio_button :group_id, group.id %>
    <%= form.label group.name %>
  <% end %>
  <%= form.submit "Update" %>
<% end %>

app/views/sources/index.html.erb
<h1>Subscriptions List</h3>
<%= render @sources %>

app/views/sources/show.html.erb
<h1>Latest Posts from <%= link_to @source.name, @source.url %></h1>

<% if @source.group_id %>
  <p>Categorized under: <%= @source.group.name %>
<% else %>
  <p>Uncategorized
<% end %>

<%= link_to "Edit", edit_source_path(@source) %></p>

<%= render @source.feed_entries.order(published_at: :desc) %>

app/views/users/new.html.erb
<%= render "sign_up", user: @user %>